### ISSUE TITLE
Stripe export changed

### ISSUE THREAD

**Issue by BerndTWT** [EverHype-Systems/stripe-lexoffice-csv#1]
Hi,

if you export "All Transactions" from your stripe accout you will now get 17 instead of 16 columns. So you have to modify some inices in the script to assign the correct data.

`

        customer = getCustomerByPayment(source)
        accounting_date = line[9]
        value_date = line[10]
        description = line[11]
`

Thank you for the script!

**Comment by adrijanb** [comment]
Hi @BerndTWT ,

sorry for not responding to your issue. Somehow i was not notified by github..
I fixed the issue. 

;)
